# Generated by Django 4.1.7 on 2025-03-20 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commodity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(verbose_name="User ID")),
                (
                    "recipient_name",
                    models.CharField(max_length=100, verbose_name="Recipient Name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=200, verbose_name="Address Line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Address Line 2",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "region",
                    models.CharField(max_length=100, verbose_name="Region/State"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="United Kingdom", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Address"),
                ),
            ],
            options={
                "verbose_name": "Delivery Address",
                "verbose_name_plural": "Delivery Addresses",
            },
        ),
        migrations.CreateModel(
            name="OrderInfos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.FloatField(verbose_name="Total Price")),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Creation Date"),
                ),
                ("user_id", models.IntegerField(verbose_name="User ID")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("shipping", "Shipping"),
                            ("delivered", "Delivered"),
                            ("returning", "Returning"),
                        ],
                        default="pending_payment",
                        max_length=20,
                        verbose_name="Order Status",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Payment ID"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="stripe", max_length=20, verbose_name="Payment Method"
                    ),
                ),
                (
                    "delivery_address",
                    models.ForeignKey(
                        blank=True,
                        db_column="delivery_address_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shopper.deliveryaddress",
                        verbose_name="Delivery Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(verbose_name="Product ID")),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Product Name"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopper.orderinfos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.CreateModel(
            name="CartInfos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("user_id", models.IntegerField(verbose_name="User ID")),
                (
                    "commodityInfos_id",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="commodity.commodityinfos",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
    ]
