# Generated by Django 4.1.7 on 2025-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
