# Generated by Django 4.1.7 on 2025-03-20 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Types",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "firsts",
                    models.CharField(
                        max_length=100, verbose_name="First-level Category"
                    ),
                ),
                (
                    "seconds",
                    models.CharField(
                        max_length=100, verbose_name="Second-level Category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Type",
                "verbose_name_plural": "Product Types",
                "unique_together": {("firsts", "seconds")},
            },
        ),
        migrations.CreateModel(
            name="CommodityInfos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Product Name")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Stock")),
                ("sold", models.IntegerField(default=0, verbose_name="Sold Quantity")),
                ("likes", models.IntegerField(verbose_name="Collection Count")),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Launch Date"),
                ),
                ("img", models.FileField(upload_to="imgs", verbose_name="Main Image")),
                (
                    "details",
                    models.FileField(
                        upload_to="details", verbose_name="Product Details"
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="commodity.types",
                        verbose_name="Product Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Information",
                "verbose_name_plural": "Product Information",
            },
        ),
    ]
